# Generated by Django 3.2.5 on 2021-08-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='عنوان تصویر ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='News/NewsPhoto/', verbose_name='تصویر ')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'افزودن تصویر',
            },
        ),
    ]
