# Generated by Django 3.2.5 on 2021-08-14 21:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='عنوان متن ')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن ')),
            ],
            options={
                'verbose_name': 'متن',
                'verbose_name_plural': 'افزودن متن',
            },
        ),
    ]
