# Generated by Django 3.2.5 on 2021-08-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newstext'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='عنوان صدا ')),
                ('voice', models.FileField(blank=True, null=True, upload_to='News/NewsVoice/', verbose_name='صدا ')),
            ],
            options={
                'verbose_name': 'صدا',
                'verbose_name_plural': 'افزودن صدا',
            },
        ),
    ]
