# Generated by Django 3.2.5 on 2021-08-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsvideo',
            name='connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newsphoto'),
        ),
    ]
