# Generated by Django 3.2.5 on 2021-08-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsvideo_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsvideo',
            name='connect',
        ),
    ]
