# Generated by Django 3.2.5 on 2021-08-14 22:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newsvideo_connect'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='عنوان اخبار ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='News/NewsPhoto/', verbose_name='تصویر ')),
                ('video', models.FileField(blank=True, null=True, upload_to='News/NewsVideo/', verbose_name='ویدیو ')),
                ('voice', models.FileField(blank=True, null=True, upload_to='News/NewsVoice/', verbose_name='صدا ')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن ')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'افزودن تصویر',
            },
        ),
        migrations.DeleteModel(
            name='NewsPhoto',
        ),
        migrations.DeleteModel(
            name='NewsText',
        ),
        migrations.DeleteModel(
            name='NewsVideo',
        ),
        migrations.DeleteModel(
            name='NewsVoice',
        ),
    ]
