# Generated by Django 3.2.5 on 2021-08-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210815_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'اخبار', 'verbose_name_plural': 'افزودن اخبار'},
        ),
    ]
