# Generated by Django 3.2.5 on 2021-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='عنوان اخبار '),
        ),
    ]
