# Generated by Django 3.2.5 on 2021-08-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=999, null=True, verbose_name='کد ')),
                ('discount_percent', models.IntegerField(blank=True, default=0, null=True, verbose_name='درصد تخفیف ')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'کد',
                'verbose_name_plural': 'کد تخفیف',
            },
        ),
    ]
