# Generated by Django 3.2.5 on 2021-08-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountCode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت تخفیف  '),
        ),
    ]
