# Generated by Django 3.2.5 on 2021-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountCode', '0004_users_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='کد '),
        ),
        migrations.AlterField(
            model_name='users_discountcode',
            name='code',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='کد '),
        ),
    ]
