# Generated by Django 3.2.5 on 2021-07-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of payment')),
                ('total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total price')),
                ('tracking_code', models.TextField(blank=True, null=True, verbose_name='Tracking code')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is paid')),
            ],
            options={
                'verbose_name': 'سبد',
                'verbose_name_plural': 'سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=999, null=True, verbose_name='Price')),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount price')),
                ('discount_percent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount percent %')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is paid')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='Owner')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
