# Generated by Django 3.2.5 on 2021-07-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0002_cart_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digitalordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=999, null=True, verbose_name='Price')),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount price')),
                ('discount_percent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount percent %')),
                ('digital_or_physical', models.BooleanField(blank=True, default=False, null=True, verbose_name='Digital or physical ?')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is paid')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='Owner')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
