# Generated by Django 3.2.5 on 2021-07-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210718_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalordering',
            name='digital_or_physical',
        ),
    ]
