# Generated by Django 3.2.5 on 2021-07-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_digitalordering_digital_or_physical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalordering',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات دیجیتالی'},
        ),
        migrations.RemoveField(
            model_name='digitalordering',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='digitalordering',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='digitalordering',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of payment'),
        ),
    ]
