# Generated by Django 3.2.5 on 2021-07-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0005_auto_20210718_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physicalproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=999, null=True, verbose_name='Price')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of payment')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is paid')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('Post_status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Post status')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='Owner')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات فیزیکی',
            },
        ),
    ]
