# Generated by Django 3.2.5 on 2021-07-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_physicalproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalproducts',
            old_name='Post_status',
            new_name='post_status',
        ),
    ]
