# Generated by Django 3.2.5 on 2021-07-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0008_auto_20210718_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت پرداخت '),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر '),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت '),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='جمع کل '),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tracking_code',
            field=models.TextField(blank=True, null=True, verbose_name='کد پیگیری '),
        ),
        migrations.AlterField(
            model_name='digitalordering',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='خریدار '),
        ),
        migrations.AlterField(
            model_name='digitalordering',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت پرداخت '),
        ),
        migrations.AlterField(
            model_name='digitalordering',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت '),
        ),
        migrations.AlterField(
            model_name='digitalordering',
            name='price',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='digitalordering',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول '),
        ),
        migrations.AlterField(
            model_name='physicalproducts',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس '),
        ),
        migrations.AlterField(
            model_name='physicalproducts',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='خریدار '),
        ),
        migrations.AlterField(
            model_name='physicalproducts',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت پرداخت '),
        ),
        migrations.AlterField(
            model_name='physicalproducts',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت '),
        ),
        migrations.AlterField(
            model_name='physicalproducts',
            name='post_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت ارسال '),
        ),
        migrations.AlterField(
            model_name='physicalproducts',
            name='price',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='physicalproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول '),
        ),
    ]
