# Generated by Django 3.2.5 on 2021-08-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20210822_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='address',
        ),
    ]
