# Generated by Django 3.2.5 on 2021-08-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_course_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='PostalCode',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='کد پستی '),
        ),
        migrations.AddField(
            model_name='course',
            name='reciver',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='گیرنده '),
        ),
        migrations.AddField(
            model_name='physical',
            name='PostalCode',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='کد پستی '),
        ),
        migrations.AddField(
            model_name='physical',
            name='reciver',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='گیرنده '),
        ),
    ]
