# Generated by Django 3.2.5 on 2021-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_auto_20210831_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discountCode',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف  '),
        ),
    ]
