# Generated by Django 3.2.5 on 2021-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_cart_discountcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='PostalCode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='address',
        ),
        migrations.RemoveField(
            model_name='course',
            name='post_status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reciver',
        ),
        migrations.AlterField(
            model_name='cart',
            name='discountCode',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف اعمال '),
        ),
    ]
