# Generated by Django 3.2.5 on 2021-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0018_auto_20210903_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=900, null=True, verbose_name='آدرس url '),
        ),
        migrations.AlterField(
            model_name='digital',
            name='price',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='digital',
            name='slug',
            field=models.SlugField(blank=True, max_length=900, null=True, verbose_name='آدرس url '),
        ),
        migrations.AlterField(
            model_name='physical',
            name='PostalCode',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='کد پستی '),
        ),
        migrations.AlterField(
            model_name='physical',
            name='price',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='physical',
            name='reciver',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='گیرنده '),
        ),
        migrations.AlterField(
            model_name='physical',
            name='slug',
            field=models.SlugField(blank=True, max_length=900, null=True, verbose_name='آدرس url '),
        ),
    ]
