# Generated by Django 3.2.5 on 2021-07-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=999, null=True, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='TiTle')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('image', models.TextField(blank=True, null=True, verbose_name='Image')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت  ما',
            },
        ),
    ]
