# Generated by Django 3.2.5 on 2021-07-18 01:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0002_auto_20210718_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='LogoWebSite', verbose_name='لوگو سایت '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='api',
            field=models.TextField(blank=True, null=True, verbose_name=' آدرس وب سرویس پنل اسمس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='ایمیل '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='آیدی اینستاگرام '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='نام سایت '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='number',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='شماره پنل اسمس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='password',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='پسورد پنل اسمس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='تلفن پشتیبانی '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='آیدی تلگرام '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms_and_Conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='قوانین و شرایط '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='toekn_zarinpal',
            field=models.TextField(blank=True, null=True, verbose_name='توکن زرین پال '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='username',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='یوزرنیم پنل اسمس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='تلفن واتساپ '),
        ),
    ]
