# Generated by Django 3.2.5 on 2021-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0005_sitesettings_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon', verbose_name='آیکون سایت '),
        ),
    ]
