# Generated by Django 3.2.5 on 2021-09-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0006_sitesettings_favicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='number',
            new_name='number_sms',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='api',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='password',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='username',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='token_sms',
            field=models.TextField(blank=True, null=True, verbose_name=' توکن پنل اسمس '),
        ),
    ]
