# Generated by Django 3.2.5 on 2021-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0007_auto_20210906_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سایت '),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='keyWord',
            field=models.TextField(blank=True, null=True, verbose_name='کلمه های کلیدی '),
        ),
    ]
