# Generated by Django 3.2.5 on 2021-09-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0010_auto_20210920_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background', verbose_name='تصویر زمینه '),
        ),
    ]
