# Generated by Django 3.2.5 on 2021-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0011_sitesettings_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address_sms',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='آدرس پنل اسمس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='ایمیل '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='آیدی اینستاگرام '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='number_sms',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='شماره پنل اسمس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='password_sms',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name=' رمز پنل اسمس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='تلفن پشتیبانی '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='آیدی تلگرام '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='نام سایت '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='username_sms',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name=' یوزرنیم پنل اسمس '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='لینک واتساپ '),
        ),
    ]
