# Generated by Django 3.2.5 on 2021-07-17 20:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pubdate', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Pub date')),
                ('title', models.CharField(blank=True, max_length=999, null=True, verbose_name='TiTle')),
                ('image', models.ImageField(blank=True, upload_to='blogImage', verbose_name='Image')),
                ('TimeRead', models.IntegerField(blank=True, default=0, null=True, verbose_name='Time to Read')),
                ('slug', models.CharField(blank=True, max_length=999, null=True, unique=True, verbose_name='Slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'مطلب',
                'verbose_name_plural': 'وبلاگ',
            },
        ),
    ]
