# Generated by Django 3.2.5 on 2021-08-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='TimeRead',
        ),
    ]
