# Generated by Django 3.2.5 on 2021-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210914_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=900, null=True, unique=True, verbose_name='آدرس url وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='عنوان '),
        ),
    ]
