# Generated by Django 3.2.5 on 2021-07-17 20:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='aboutUs-image', verbose_name='Photo')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
