# Generated by Django 3.2.5 on 2021-07-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=999, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=999, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=999, null=True, verbose_name='Subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
