# Generated by Django 3.2.5 on 2021-08-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='CoursePrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت دوره '),
        ),
    ]
