# Generated by Django 3.2.5 on 2021-08-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_courseslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CourseStatus',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا دوره  به اتمام رسیده؟ '),
        ),
    ]
