# Generated by Django 3.2.5 on 2021-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_coursestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='CourseDuration',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='مدت زمان دوره : 45:25:00 '),
        ),
    ]
