# Generated by Django 3.2.5 on 2021-08-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_courseduration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='Courses/Videos/', verbose_name=' ویدیو')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos_set', to='courses.courses', verbose_name=' دوره')),
            ],
            options={
                'verbose_name': 'ویدیو',
            },
        ),
    ]
