# Generated by Django 3.2.5 on 2021-09-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'ویدیو', 'verbose_name_plural': 'ویدیو ها'},
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name=' عنوان ویدیو'),
        ),
    ]
