# Generated by Django 3.2.5 on 2021-09-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210906_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=' ویدیو را می توان رایگان دانلود کرد؟'),
        ),
    ]
