# Generated by Django 3.2.5 on 2021-09-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_videos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='status',
        ),
    ]
