# Generated by Django 3.2.5 on 2021-09-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_videos_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='Courses/IntroductionVideo/', verbose_name='  ویدیو معرفی')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IntroductionVideo_set', to='courses.courses', verbose_name=' دوره')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو های معرفی',
            },
        ),
    ]
