# Generated by Django 3.2.5 on 2021-09-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_introductionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='keyWord',
            field=models.TextField(blank=True, null=True, verbose_name='کلمه های کلیدی '),
        ),
    ]
