# Generated by Django 3.2.5 on 2021-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CourseName',
            field=models.CharField(blank=True, max_length=999, null=True, unique=True, verbose_name='نام دوره '),
        ),
        migrations.AlterField(
            model_name='courses',
            name='CourseStatus',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت نمایش '),
        ),
    ]
