# Generated by Django 3.2.5 on 2021-09-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210919_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='videos',
        ),
    ]
