# Generated by Django 3.2.5 on 2021-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_courses_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CourseDuration',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='مدت زمان دوره : 45:25:00 '),
        ),
        migrations.AlterField(
            model_name='courses',
            name='CourseLevel',
            field=models.CharField(blank=True, default='مقدماتی', max_length=900, null=True, verbose_name='سطح دوره '),
        ),
        migrations.AlterField(
            model_name='courses',
            name='CourseName',
            field=models.CharField(blank=True, max_length=900, null=True, unique=True, verbose_name='نام دوره '),
        ),
        migrations.AlterField(
            model_name='courses',
            name='CourseSlug',
            field=models.SlugField(blank=True, max_length=900, null=True, verbose_name='آدرس url '),
        ),
    ]
