# Generated by Django 3.2.5 on 2021-08-10 22:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=999, null=True, verbose_name='نام ')),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات ')),
            ],
        ),
    ]
