# Generated by Django 3.2.5 on 2021-08-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0002_aboutme_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'درباره من', 'verbose_name_plural': 'درباره من'},
        ),
    ]
