# Generated by Django 3.2.5 on 2021-09-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0003_alter_aboutme_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='keyWord',
            field=models.TextField(blank=True, null=True, verbose_name='کلمه های کلیدی '),
        ),
    ]
