# Generated by Django 3.2.5 on 2021-08-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
