# Generated by Django 3.2.5 on 2021-09-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210811_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keyWord',
            field=models.TextField(blank=True, null=True, verbose_name='کلمه های کلیدی '),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital_or_physical',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=' محصول فیزیکی است ؟ '),
        ),
    ]
